[client]
showErrorDetails = "none"

[theme]
primaryColor="#4e9492"
backgroundColor="#182241"
secondaryBackgroundColor="#1d1e33"
textColor="#9c802e"

[runner]
# Allows you to type a variable or string by itself in a single line of
# Python code to write it to the app.
#
# Default: true
magicEnabled = true

# Handle script rerun requests immediately, rather than waiting for
# script execution to reach a yield point.
#
# This makes Streamlit much more responsive to user interaction, but it
# can lead to race conditions in apps that mutate session_state data
# outside of explicit session_state assignment statements.
#
# Default: true
fastReruns = true